### ISSUE TITLE
locale="ms" is not taking any effect

### ISSUE THREAD

**Issue by kienhawlee** [shipshapecode/ember-flatpickr#1214]
I'm currently working with ember-flatpickr and setting up a different locale based on language selection. As I tested, the `ms` locale doesn't seem to be working as expected.

For `zh`, it was translated perfectly fine:
<img width="245" alt="Screenshot 2022-06-27 at 4 39 36 PM" src="https://user-images.githubusercontent.com/76933975/175897622-8c3d8c67-2a00-406d-ac0d-242c31afc4a3.png">

However, for `ms` it doesn't seem like it is translating and it will use the default locale (`en`):
<img width="248" alt="Screenshot 2022-06-27 at 4 39 22 PM" src="https://user-images.githubusercontent.com/76933975/175897669-866ad6f0-0e00-497c-b0e5-6a85fc7e4537.png">

Seeking your help to see what could possibly go wrong with using the `ms` locale?

Code:

<img width="158" alt="Screenshot 2022-06-27 at 4 39 03 PM" src="https://user-images.githubusercontent.com/76933975/175898224-6866f308-eca7-4f77-a55d-d3882e0786c9.png">

My ember-flatpickr version: `2.16.4` which requires flatpickr version: `4.6.3`
My ember cli version: `3.12.1`
My ember-cli-build:
    `flatpickr: {
      locales: ['zh', 'ms']
    }`

P/S: I'm referring to the list of locales [here](https://github.com/flatpickr/flatpickr/tree/master/src/l10n)

**Comment by AhamedFrontEndDeveloper** [comment]
This should be the issue with "flatpickr" itself. I have raised this issue with flatpickr and raised a PR as well.
https://github.com/flatpickr/flatpickr/issues/2737 @kienhawlee

**Comment by rwwagner90** [comment]
Closing this, since it is an issue upstream.
