### ISSUE TITLE
Change action if value is empty

### ISSUE THREAD

**Issue by marucjmar** [shipshapecode/ember-flatpickr#122]
Hi,

When value is empty action not send but the code is break this. I use only DDAU, and my action not set empty array. 

Could change this condition: 

```
  _onChange(selectedDates, dateStr, instance) {
    if (selectedDates && selectedDates.length > 0) {
      this.sendAction('onChange', selectedDates, dateStr, instance);
    }
  },
```

 to:
```
  _onChange(selectedDates, dateStr, instance) {
    if (selectedDates) {
      this.sendAction('onChange', selectedDates, dateStr, instance);
    }
  },
````
?

Thanks

**Comment by rwwagner90** [comment]
@marucjmar is it possible to deselect dates? Not sure how this check causes an issue. If it's related to the other issues and PRs on here, we'll have a fix soon.

**Comment by rwwagner90** [comment]
I removed the `if` entirely in version 1.1.7. Please give it a try!
