### ISSUE TITLE
dateFormat doesn't work with the readonly helper

### ISSUE THREAD

**Issue by humanchimp** [shipshapecode/ember-flatpickr#125]
Configuring the component in the following way results in the text input containing an unformatted date.

```handlebars
{{ember-flatpickr
  value=(readonly dateValue)
  onChange=(action (mut dateValue))
  dateFormat="m/d/Y"}}
```

If I remove the `readonly` helper, the date gets formatted, but the value of `dateValue` gets cast to a string.

**Comment by rwwagner90** [comment]
@humanchimp I suspect this might have to do with the same issue everyone is reporting here. Once flatpickr releases a new version, we'll see if this issue still exists.

**Comment by humanchimp** [comment]
Ah, ok. Sorry to report an issue that is already on record. If this is a duplicate, please feel free to close it.

**Comment by rwwagner90** [comment]
@humanchimp can you try installing version 1.1.7 and seeing if the issue is resolved please?

**Comment by humanchimp** [comment]
It seems like my issue is different than what I described. I'm going to close this issue and open a new one later, if necessary.
