### ISSUE TITLE
Not compatible with Node 4.x

### ISSUE THREAD

**Issue by kevinansfield** [shipshapecode/ember-flatpickr#143]
Due to the use of a [spread operator in index.js](https://github.com/shipshapecode/ember-flatpickr/blob/master/index.js#L29) this addon will cause the ember build to fail when using the 4.x LTS version of Node.js.

**Comment by rwwagner90** [comment]
Hi @kevinansfield, is there a reason you cannot update to at least node 5? node 8 will likely be out sometime soon, and 4 is quite old. I do not intend to really support it.

**Comment by kevinansfield** [comment]
In this case it's for [Ghost](https://ghost.org) where we adhere to the Node LTS schedule. 4.x is currently our recommended version (that will change soon) but we need to support all active and maintained LTS releases. We don't have the luxury of having a central service where we're fully in control of the environment so we need to cater for the complete range of possible developer environments.

**Comment by kevinansfield** [comment]
FYI, I think usage in Ghost is a moot point now, it looks like we'll be going with `ember-power-datepicker` to avoid some bugs in `flatpickr` itself.

**Comment by rwwagner90** [comment]
@kevinansfield what were the bugs with flatpickr itself? Anything we could fix in the wrapper here? The flatpickr guy has been good at fixing bugs as I report them too, if you'd like to pursue this further. Would be cool for Ghost to use it 😄
