### ISSUE TITLE
Time Pick

### ISSUE THREAD

**Issue by chewtoys** [shipshapecode/ember-flatpickr#146]
Could you implement something like this for time?

https://weareoutman.github.io/clockpicker/

right now its kind of MEH by typing it in.

**Comment by rwwagner90** [comment]
Hi @chewtoys that would probably be a feature to request in flatpickr itself, rather than here, but we could potentially add it here.

**Comment by rwwagner90** [comment]
@chewtoys would you like to request something like that in flatpickr itself?

**Comment by chewtoys** [comment]
@rwwagner90 yep I requested it there, hopefully it gets added

**Comment by rwwagner90** [comment]
Closing this, in favor of implementing in flatpickr itself then. Issue can be found here https://github.com/chmln/flatpickr/issues/764
