### ISSUE TITLE
Ember serve fails after installing addon

### ISSUE THREAD

**Issue by Mithrilhall** [shipshapecode/ember-flatpickr#151]
I'm trying to use ember-flatpickr in my project and get the following error when trying to run `ember s` after installing the addon. Any idea how I can resolve this?

P.S - I'm using fastboot but I'm starting ember via `ember s`.

```
X@X ~/source-git/test-website $ ember s
Cannot read property 'import' of undefined
TypeError: Cannot read property 'import' of undefined
    at /home/X/source-git/test-website/node_modules/ember-cli-node-assets/lib/perform-imports.js:8:16
    at Array.forEach (native)
    at performImports (/home/X/source-git/test-website/node_modules/ember-cli-node-assets/lib/perform-imports.js:6:12)
    at Class.performImports (/home/X/source-git/test-website/node_modules/ember-cli-node-assets/index.js:14:37)
    at Class.included (/home/X/source-git/test-website/node_modules/ember-cli-node-assets/index.js:9:10)
    at Class.superWrapper [as included] (/home/X/source-git/test-website/node_modules/core-object/lib/assign-properties.js:32:18)
    at /home/X/source-git/test-website/node_modules/ember-cli/lib/models/addon.js:254:34
    at Array.map (native)
    at Class.eachAddonInvoke (/home/X/source-git/test-website/node_modules/ember-cli/lib/models/addon.js:252:24)
    at Class.included (/home/X/source-git/test-website/node_modules/ember-cli/lib/models/addon.js:429:10)
```

**Comment by rwwagner90** [comment]
Hi @Mithrilhall, sorry to hear you are having issues, and sorry for the late reply. Is this in an app, addon, or engine? 

Are you using ember-cli-node-assets yourself?

From the stack trace, it appears the issue is this https://github.com/dfreeman/ember-cli-node-assets/blob/master/lib/perform-imports.js#L8
So the config passed is undefined and therefore `config.import` blows up.

Perhaps missing a `this._super.included.apply(this, arguments);` in an included hook?

**Comment by Mithrilhall** [comment]
This is an app. I'll take a look around to see if we're missing `this._super.included.apply(this, arguments);` anywhere.

**Comment by rwwagner90** [comment]
@Mithrilhall are you attempting to pass a config for flatpickr in? If so, where and what are you passing? If you are in an app, the included hook is not the issue, that is for addons.

**Comment by Mithrilhall** [comment]
We currently have ember-flatpickr in one of our addons that is used in the app. I'll take a look to see if we have any hooks that are not setup correctly.

**Comment by rwwagner90** [comment]
@Mithrilhall ah, then yes, it is an issue with the included hook there, and you need to make sure `ember-flatpickr` is in deps, not devDeps as well.

**Comment by Mithrilhall** [comment]
I've added `"ember-flatpickr": "1.1.7",` to my addons package.json and I'm getting the following error when trying to start `ember s` from my app:

```
Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at Class.flatpickr (/home/X/source-git/test-website/node_modules/ember-flatpickr/index.js:21:41)
    at Object.config (/home/X/source-git/test-website/node_modules/ember-cli-node-assets/lib/normalize-package-config.js:14:66)
    at /home/X/source-git/test-website/node_modules/ember-cli-node-assets/lib/tree-for.js:24:22
    at Array.map (native)
    at treeFor (/home/X/source-git/test-website/node_modules/ember-cli-node-assets/lib/tree-for.js:23:24)
    at Class.treeForVendor (/home/X/source-git/test-website/node_modules/ember-cli-node-assets/index.js:18:37)
    at Class._treeFor (/home/X/source-git/test-website/node_modules/ember-cli/lib/models/addon.js:371:33)
    at Class.treeFor (/home/X/source-git/test-website/node_modules/ember-cli/lib/models/addon.js:339:21)
    at /home/X/source-git/test-website/node_modules/ember-cli/lib/models/addon.js:254:34
    at Array.map (native)
```

**Comment by rwwagner90** [comment]
@Mithrilhall is it in dependencies or devDependencies? It must be in dependencies.

**Comment by Mithrilhall** [comment]
I have it in dependencies and I've added this

```
app.import( app.bowerDirectory + '/flatpickr/dist/js/flatpickr.min.js' );
app.import( app.bowerDirectory + '/flatpickr/dist/js/flatpickr.min.css' );
```
to index.js in my addon but it didn't seem to make a difference.

**Comment by rwwagner90** [comment]
@Mithrilhall you don't need that. Can you please copy your `index.js` here for me to see?

**Comment by Mithrilhall** [comment]
```
/* jshint node: true */
'use strict';

module.exports = {
    name: 'test-controls',

    included: function ( app ) {
        this._super.included( app );

        app.import( app.bowerDirectory + '/rxjs/dist/rx.all.min.js' );

        app.import( app.bowerDirectory + '/typeahead.js/dist/typeahead.bundle.js' );

        app.import( app.bowerDirectory + '/select2/select2.js' );
        app.import( app.bowerDirectory + '/select2/select2.css' );
        app.import( app.bowerDirectory + '/select2/select2.png', {destDir: 'assets'} );
        app.import( app.bowerDirectory + '/select2/select2x2.png', {destDir: 'assets'} );
        app.import( app.bowerDirectory + '/select2/select2-spinner.gif', {destDir: 'assets'} );

        app.import( app.bowerDirectory + '/fine-uploader/dist/fine-uploader.min.js' );
        app.import( app.bowerDirectory + '/fine-uploader/dist/fine-uploader.min.css' );
        app.import( app.bowerDirectory + '/bootstrap/dist/js/bootstrap.js' );
    }
};
```

I've removed the two lines that you said I don't need.

**Comment by rwwagner90** [comment]
@Mithrilhall replace `this._super.included( app );` with `this._super.included.apply(this, arguments);`.

**Comment by rwwagner90** [comment]
Which version of ember and ember-cli are you on?

**Comment by Mithrilhall** [comment]
`ember-cli: 2.10.1` & `"ember": "~2.11.2"`

**Comment by rwwagner90** [comment]
I would expect it to work if you replace `this._super.included( app );` with `this._super.included.apply(this, arguments);`.

As a side note, you're going to want to use `this.import` instead of `app.import` for all of those imports.

**Comment by Mithrilhall** [comment]
@rwwagner90 Thanks for the help. I'll poke around a bit and see if I can get this working properly. I'm 100% sure it's something in my addon that is causing the issue.

**Comment by rwwagner90** [comment]
@Mithrilhall did you try changing it to `this._super.included.apply(this, arguments)`?

**Comment by Mithrilhall** [comment]
I did but it didn't work. I think I have something else in my addon that's causing an issue. I appreciate all the help.
