### ISSUE TITLE
Allow tests API to accept an html element

### ISSUE THREAD

**Issue by AmauryD** [shipshapecode/ember-flatpickr#1557]
Hello,

Is it possible to allow the tests APIs to allow an html element in addition of a CSS selector ?

```js
const element = document.querySelector(...);
setFlatpickrDate(element);
```

I use ember-cli-page-object that uses Jquery selectors internally. So they are not compatible with the tests helpers in this library.
I used `findOne(...).flatpickrInput._flatpickr.setDate(date ?? new Date(), true);` as a fix.  But i would be nice to have a more convenient API.

I can do a PR if needed.

Thank you

**Comment by RobbieTheWagner** [comment]
@AmauryD sorry for the huge delay on this. If you would like to open a PR, I would be glad to accept it!

**Comment by AmauryD** [comment]
> @AmauryD sorry for the huge delay on this. If you would like to open a PR, I would be glad to accept it!

No problem ! Thank's for your reply. I just made the PR.

**Comment by AmauryD** [comment]
merged
