### ISSUE TITLE
BUG: time picker does not work

### ISSUE THREAD

**Issue by wmadden** [shipshapecode/ember-flatpickr#158]
`onChange()` is called with the correct Date value, but when the value is passed back in to the `ember-flatpickr` component its time component appears to be discarded.

Incidentally, the `ember-flatpickr` demo page includes a time picker but its value is immediately discarded. Very pretty, but completely useless.

**Comment by wmadden** [comment]
Here is a twiddle demonstrating this bug: https://ember-twiddle.com/a1545ed006124f8ea8191b307fef525c?openFiles=templates.application.hbs%2C

After a little investigation, the issue is that the `dateFormat` value supplied to Flatpickr causes it to display date-time values using _only_ the date string. Supplying a default `dateFormat` param of `null` solves the problem.

**Comment by wmadden** [comment]
There might be a lesson here regarding the other default values: perhaps it's better _not_ to supply anything and let Flatpickr implement its own defaults than to supply defaults that are hardcoded into `ember-flatpickr`.

**Comment by rwwagner90** [comment]
@wmadden the default `dateFormat` is the same as the one defined by flatpickr itself. I think you would have to pass `null` either way to override it. It's worth noting, that the string display in the input, is not the full date value, just a display string, so the time is likely preserved in the actual value, I would assume.

![screen shot 2017-04-26 at 8 46 16 am](https://cloud.githubusercontent.com/assets/2640861/25435106/fb2a70c2-2a5c-11e7-8ad4-bdfe658018f0.png)

You can also use `altInput` and `altFormat` to have different values displayed to the user and sent to the server.

With all that in mind, I think this issue could be closed?

**Comment by wmadden** [comment]
@rwwagner90 you're right, the `dateFormat` string is the same default documented by flatpickr. However, if flatpickr doesn't receive a `dateFormat` config option (specifically if it's `undefined` - `null` makes it throw an error) and if `enableTime` is true then flatpickr will use a formatting string that includes the time segment. If `dateFormat` is supplied and `enableTime` is true, flatpickr will use the given date format string (and hide the time segment).

**Comment by wmadden** [comment]
You might argue that it's a flatpickr bug, I'm not sure. But at the moment I'm doing `{{ember-flatpickr dateFormat=undefined ...}}` which isn't great for consumers of `ember-flatpickr`

**Comment by rwwagner90** [comment]
I used some of the ideas from your PR to fix this issue 👍
