### ISSUE TITLE
RFC: How should we pass configuration options to flatpickr?

### ISSUE THREAD

**Issue by wmadden** [shipshapecode/ember-flatpickr#164]
## The problem

`ember-flatpickr` needs to pass configuration options to `flatpickr`, which are provided as attributes to the ember-flatpickr component. Ember doesn't have an idiomatic way to read all given attributes to a component, so it currently reads a [predefined array](https://github.com/shipshapecode/ember-flatpickr/blob/93dc7e419f872feb83292674fab59ea9a9c8bc32/addon/components/ember-flatpickr.js#L55-L89) of config options from its properties. Since any property you _don't_ supply would cause it to provide the corresponding config option to flatpickr as `null`, all properties are given a default value equal to the flatpickr default.

This has two unfortunate consequences:

1. The list of possible config options and their default values gets out of date, and needs to be updated in `ember-flatpickr`
2. Flatpickr interprets an absent config option differently to a config option set to its default value *

_* The specific case we observed is that if `enableTime` is true, flatpickr will use a `dateFormat` string that includes a formatted time as well as date, unless the user supplies their own `dateFormat` string. ([See here](https://github.com/chmln/flatpickr/blob/359029cdc2a088e60d0933e236a094838f1cc003/src/flatpickr.js#L1432-L1436))_

## Possible solutions

These are some options we discussed to avoid these problems.

### 1. Don't provide defaults, pass only options that're explicitly provided

- We keep an array of option names
- Instead of doing `getProperties(allOptions)`, we filter `Object.keys(this)` for known options and only pass the ones that are present as keys

#### Pros:

- Don't have to pass defaults for unspecified options
- As a result, default values cannot get out of date
- Backwards compatible

#### Cons:

- Have to maintain the list of options

### 2. Accept a hash of options to pass to flatpickr

- We take an explicit options hash as an attribute
- We pass the hash with no preprocessing directly to flatpickr

#### Example usage

```hbs
{{ember-flatpickr value=myDate options=(hash enableTime=true dateFormat='d/m/Y')}}
```

#### Pros:

- We don't have to maintain a list of possible options
- We don't have to maintain default values
- (This would allow us to delete about 40% of `ember-flatpickr`'s code :trollface:)

#### Cons:

- The syntax to invoke the component is a bit cumbersome, now including `options=(hash...)`
- Some open questions around `onChange` and `value` attributes, which don't belong in the options hash
- Not backwards compatible

### 3. Use a helper to render the component (which accepts hash options)

- Instead of exposing the `ember-flatpickr` component directly, we wrap it with a helper
- We take the helper's hash parameters as options for flatpickr, optionally extracting `value` and `onChange` as special arguments

#### Example usage

```hbs
{{ember-flatpickr value=myDate enableTime=true dateFormat="d/m/Y"}}
```

#### Pros:

- We don't have to maintain a list of possible options
- We don't have to maintain default values
- (Also allows us to delete ~40% of the code)
- Backwards compatible

#### Cons:

- Adds a helper to the codebase, making it slightly more complex
- I'm not 100% sure if this approach would work, or what the semantics are for addons exposing helpers that render private components

**Comment by rwwagner90** [comment]
I solved this by using `this.attrs`. Not sure why the Ember team recommends against it, but rwjblue said it was okay 😄
