### ISSUE TITLE
Using external elements

### ISSUE THREAD

**Issue by Mithrilhall** [shipshapecode/ember-flatpickr#166]
Is it possible to use the external elements example on [using external elements](https://chmln.github.io/flatpickr/examples/#flatpickr-external-elements) page?

Also, in the  [external elements example](https://chmln.github.io/flatpickr/examples/#flatpickr-external-elements); is it possible to have the buttons disappear when _disableMobile_ is set to true?

**Comment by rwwagner90** [comment]
@Mithrilhall should be able to, I think. Not sure. Why did you close the issue? Figure it out?

**Comment by Mithrilhall** [comment]
I figured it out using flatpickr through bower. I basically need to check 'isMobile'. 

Is it possible to access the underlying flatpickr in my component.js if I'm using this addon?

**Comment by rwwagner90** [comment]
@Mithrilhall yep! Check https://github.com/shipshapecode/ember-flatpickr#flatpickrref

**Comment by Mithrilhall** [comment]
@rwwagner90 Thanks! I don't know how I missed that.
