### ISSUE TITLE
Using 'allowInput' only updates the date if enter is pressed

### ISSUE THREAD

**Issue by Mithrilhall** [shipshapecode/ember-flatpickr#179]
With **allowInput** set to **true**, if the user types in a date and clicks outside of the ember-flatpickr input; the date never really updates. It appears that the user needs to hit the **enter** button for the date to actually update.

[Ember Twiddle](https://ember-twiddle.com/19302d25c184c34117ec17ade0b5b1d0)

**Comment by rwwagner90** [comment]
@Mithrilhall Isn't this probably a flatpickr issue?

**Comment by Mithrilhall** [comment]
@rwwagner90 I'm getting ready to test it now using plain old flatpickr.

**Comment by Mithrilhall** [comment]
@rwwagner90 This is indeed an issue with flatpickr. I apologize.
