### ISSUE TITLE
Using 'allowInput' requires the user to click outside of the input (twice) for focus to be lost

### ISSUE THREAD

**Issue by Mithrilhall** [shipshapecode/ember-flatpickr#180]
Using **allowInput** requires the user to click outside of the input (twice) for focus to be lost.

[Ember Twiddle](https://ember-twiddle.com/19302d25c184c34117ec17ade0b5b1d0?openFiles=templates.application.hbs%2C)

**Comment by rwwagner90** [comment]
@Mithrilhall I assume this is the same issue as the other one? Can we close it too as it's likely a flatpickr bug?

**Comment by Mithrilhall** [comment]
@rwwagner90 I don't think this is the same issue (I could be wrong). I tested this in a jsfiddle with vanilla flatpickr and it didn't have this issue. I'll recreate it and link to it in here.

**Comment by Mithrilhall** [comment]
Vanilla flatpickr doesn't appear to have this behavior.

[JSFiddle Example](https://jsfiddle.net/Mithrilhall/xpcs7dag/)

**Comment by rwwagner90** [comment]
@Mithrilhall can you please try ember-flatpickr 1.3.0? This seems to have been an issue with older flatpickr.

**Comment by Mithrilhall** [comment]
Works like a charm. Thank you @rwwagner90.
