### ISSUE TITLE
Clearing datepicker programatically

### ISSUE THREAD

**Issue by scottfisk** [shipshapecode/ember-flatpickr#185]
So far I have been unable to find a way to clear (reset back to placeholder) the datepicker programatically without using a `flatpickrRef` on my parent component.

I have tried setting `value` to `null` but due to [this if statement](https://github.com/shipshapecode/ember-flatpickr/blob/master/addon/components/ember-flatpickr.js#L123) that doesn't actually set the value in flatpickr. 

If I use a `flatpickrRef` to call `.setDate(null)` or `.clear()` the picker clears as intended.

Is my solution to use a `flatpickrRef` the best way to do this or is is possible the check in the aforementioned `value` observer could be relaxed to reset the datepicker purely with a data change. Any help is appreciated, thanks.

**Comment by rwwagner90** [comment]
Hi @scottfisk, thanks for submitting an issue. I'm not sure if we really even need the `value` stuff anymore. We could maybe use just `defaultDate`. I'd be open to a PR to fix it 😄

**Comment by rwwagner90** [comment]
I just released 1.3.1, which allows passing `null` for the date to clear it. Please give it a try!

**Comment by scottfisk** [comment]
Finally got around to trying this out. Worked great. Thanks a lot!
