### ISSUE TITLE
Setting defaultDate

### ISSUE THREAD

**Issue by Mithrilhall** [shipshapecode/ember-flatpickr#194]
Setting the time via **defaultDate** doesn't appear to work in ember-flatpickr.

[Twiddle Example (ember-twiddle)](https://ember-twiddle.com/131fece8194455a9a542ea9360174df1?openFiles=templates.application.hbs%2C)

[JSFiddle Example (flatpickr)](https://jsfiddle.net/9o1cya9t/2/)

**Comment by rwwagner90** [comment]
@Mithrilhall please use `date="8:25 AM"` and it will work. Do you need `defaultDate`?

**Comment by Mithrilhall** [comment]
Thanks @rwwagner90. *date* will work...no need for *defaultDate*.
