### ISSUE TITLE
Using altInput property prevents dynamic updating of disabled property

### ISSUE THREAD

**Issue by jleja** [shipshapecode/ember-flatpickr#195]
Example Twiddle:  https://ember-twiddle.com/ab927f989a3ae2863c08d8e9078a48ca?openFiles=templates.application.hbs%2C

When using the `altInput` property, the `disabled` property gets set once, but doesn't update if you need to programmatically toggle it.  Given the Twiddle above, the first example shows a Flatpickr instance where you can toggle a checkbox, and it will enable/disable the Flatpickr.  The same functionality should occur on the second example, which sets the `altInput` property, but doesn't update after the initial render.

**Comment by rwwagner90** [comment]
This is fixed in 2.0.2
