### ISSUE TITLE
Data-binding

### ISSUE THREAD

**Issue by ngelx** [shipshapecode/ember-flatpickr#2]
Hi, I've got a test app with a model Trip that got some attr:

```
import DS from 'ember-data';
import Ember from 'ember';

export default DS.Model.extend({
  ...
  startDate: DS.attr('date'),
  endDate: DS.attr('date'),
  ....
```

I would like to use this addon to handle the startDate and endDate attr on trip forms, so i did something like this:

```
 {{ember-flatpickr
                  altInput=true
                  altFormat="F j, Y"
                  dateFormat="M/D/Y"
                  enableTime=true
                  hourIncrement=1
                  maxDate=trip.endDate
                  minuteIncrement=10
                  timeFormat="H:m"
                  value=trip.startDate}}
```

It works as expected except for 2 things. 

1. the input is not bind to the field. That mean that when I change the date using the calendar, the model field is not updated, even i've set it on the `value` option.

2. Same for `maxDate` and `minDate`, the options are set ok on flatpickr init, but they are not updated when the values changes.

I know this addon is in a develop stage, but i want to ask if i'm doing something wrong? Are those  features going to be included on the plugin?

Thanks in advance
Angel

**Comment by rwwagner90** [comment]
@ngelx we will definitely need to support that. However, there is an `onChange` parameter where you can pass a function in. You could make this function an action to send the value back out with an action. I'll work on making this more dynamic and bound though.

**Comment by rwwagner90** [comment]
@ngelx value is now set when `onChange` is fired, so if you do `value=(mut trip.startDate)` using the `mut` helper should allow the value to be passed back out.

Alternatively, `onChange` now also fires `onChangeAction` so you could pass an action in that would set value whenever a new date is chosen.

Please let me know your thoughts on these options.

**Comment by rwwagner90** [comment]
@ngelx does this work for you now?

**Comment by ngelx** [comment]
Hey @rwwagner90 sorry for the delay. Yes the data binding is working for `value`, and i think for updating `minDate`/`maxDate` we could use the onChange. I'm only missing how can I reference one flatpickr from the other, so, let say,  when statDate changes, it automatically update the minDate from the other flatpickr.

Something similar as it is documented on the flatpickr page.

https://chmln.github.io/flatpickr/#onchange 

Thanks,

**Comment by rwwagner90** [comment]
No problem @ngelx. Are you trying to use two flatpickrs to select a start date and end date to use for a range? I think there is some more work to do to support that. Just trying to understand exactly the use case, so I can make sure to handle it.

**Comment by ngelx** [comment]
Exactly. I've got a pretty common scenario where my model is a `Trip`, and i need to set the `startDate` and the `endDate`. As usual, it should be a range and met the invariant: `startDate <= endDate`

So far i've done something like:

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                {{ember-flatpickr
                  altInput=true
                  altFormat="F j, Y"
                  dateFormat="M/D/Y"
                  enableTime=true
                  hourIncrement=1
                  maxDate=trip.endDate // <-- this should be updated when trip.endDate changes
                  minuteIncrement=10
                  timeFormat="H:m"
                  value=(mut trip.startDate)}}
              </div>
            </div>
            <div class="col-md-6">
              <div class="input-group">
                {{ember-flatpickr
                  altInput=true
                  altFormat="F j, Y"
                  enableTime=true
                  hourIncrement=1
                  minDate=trip.startDate // <-- this should be updated when trip.startDate changes
                  minuteIncrement=10
                  value=(mut trip.endDate)}}
              </div>
            </div>
          </div>


I think this could be done using the onChange function, but we need a way to identify each flatpickr. 

Thanks

**Comment by rwwagner90** [comment]
@ngelx I don't think the `onChange` function is a good place for that. We should build some sort of updates into the addon.

Wouldn't you want only the start or end date to update, but not both? With your current code, if I choose a start of 04/22 and end of 04/23, but then I decide I actually want 05/22 and 05/23, and I open the first flatpickr, I find myself unable to move the startDate anywhere.

**Comment by ngelx** [comment]
@rwwagner90 yep, i've mentioned the `onChange` option because the flatpickr.js lib document it that way, but if it is possible to integrated inside the addon, much better!

Regarding to:

> Wouldn't you want only the start or end date to update, but not both? With your current code, if I choose a start of 04/22 and end of 04/23, but then I decide I actually want 05/22 and 05/23, and I open the first flatpickr, I find myself unable to move the startDate anywhere.

The user will need to changes first the `endDate` (to 5/23), and then the `startDate` (to 5/22). Not the best UX. Maybe it would be possible to update both when needed?

**Comment by rwwagner90** [comment]
@ngelx Ah, I see the example you are talking about. I will implement something to handle this case tonight or tomorrow.

**Comment by rwwagner90** [comment]
@ngelx I implemented observers that will update the flatpickr instance when you change maxDate or minDate. I published version `0.1.0` of this addon, which should hopefully help you accomplish what you are looking for. Install it and give it a try please!

**Comment by rwwagner90** [comment]
@ngelx does everything work for you now?

**Comment by rwwagner90** [comment]
Closing this, as I have not heard from you @ngelx
