### ISSUE TITLE
Compatible with 1.13? 

### ISSUE THREAD

**Issue by jtabone16** [shipshapecode/ember-flatpickr#207]
We're finally upgrading our app to 1.13 and want to move away from using a jQuery lib for our date-time picker. Is this compatible? Couldn't find anything in the docs

**Comment by rwwagner90** [comment]
Hi @jtabone16, I'm not sure if it is compatible or not. It is only tested on LTS versions, and not written with support for 1.13 in mind. However, that does not necessarily mean it doesn't work.

I would highly recommend updating to Ember 2.8+ to at least be on an LTS version. I realize that can be a lot of work though. If you are interested in help with updating, my consulting company has experience helping with this sort of thing 😄 https://shipshape.io

What company do you work for? I'd love to at least start a conversation about working with you guys.

**Comment by rwwagner90** [comment]
@jtabone16 bump ^

**Comment by rwwagner90** [comment]
@jtabone16 since I have not heard back from you, I am going to close this. Please feel free to try it out with 1.13, and if you encounter issues, I would be glad to help fix them.
