### ISSUE TITLE
How do you implement a range plugin?

### ISSUE THREAD

**Issue by ashokaditya** [shipshapecode/ember-flatpickr#211]
Similar to this?

https://chmln.github.io/flatpickr/plugins/#rangeplugin-beta

**Comment by rwwagner90** [comment]
@ashokaditya that appears to be in beta, from the docs. Do you need two inputs do do you just want a range picker? You can set `mode` to `range` which is specified in the flatpickr docs https://chmln.github.io/flatpickr/options/.

If you really need two inputs or want to implement a custom rangePlugin, I don't think we currently support this. I would definitely be open to supporting this though. Would you be interested in submitting a PR to add this functionality?

**Comment by ashokaditya** [comment]
Thanks for your response @rwwagner90 

Yes I would require two inputs. It is more intuitive, I think. 
Like a `From` and `To` date inputs where the `To` date has to be greater than the chosen `From` date. Something like you usually see on flight booking apps. Does that make sense?

I would love to create a pull request if you agree :)

Please let me know,
Thanks.

**Comment by rwwagner90** [comment]
@ashokaditya the PR would be just to support range plugins, which should allow you to do whatever sort of ranges you want.

FWIW, you can also do this now without the plugins, but just using two `ember-flatpickr` instances.

**Comment by ashokaditya** [comment]
I'll give it a shot with two instances of ember-flatpicker and let you know how it goes, if that's okay.

**Comment by rwwagner90** [comment]
@ashokaditya not interested in adding support for rangePlugins in a PR? No pressure either way, but we should probably support it, if flatpickr supports it.

**Comment by ashokaditya** [comment]
Oh I thought you didn't want me to create a pull request. I think it is a great idea to have the range plugin support :) I would love to create a PR for this. Would you mind telling me how should I proceed?

**Comment by rwwagner90** [comment]
@ashokaditya no, I said you should create a PR. I said:
> the PR would be just to support range plugins, which should allow you to do whatever sort of ranges you want.

I definitely want to support all things flatpickr supports. Let me know what you need from me, and I am happy to help!

**Comment by ashokaditya** [comment]
@rwwagner90 I'm glad that you agree. 
I would like to know what all do I need to include in a pull request?
Is there a  specific format you prefer? Or just a simple pull request branch? 
If yes, which branch?

Ash.

**Comment by rwwagner90** [comment]
@ashokaditya I don't have anything I require for a PR, but tests would be nice.

**Comment by rwwagner90** [comment]
@ashokaditya any progress on this? Anything I can help with?

**Comment by ashokaditya** [comment]
Hi @rwwagner90. I haven't had the time to write tests yet for the PR.
I could use some help with a dummy test file if you could provide one?

Please let me know.
Thanks.

Ash

**Comment by rwwagner90** [comment]
@ashokaditya there are tests already in the repo https://github.com/shipshapecode/ember-flatpickr/tree/master/tests

**Comment by rwwagner90** [comment]
@ashokaditya are you still working on this?

**Comment by rwwagner90** [comment]
@ashokaditya I'm going to assume you are no longer working on this and close the issue. If you would like to work on it more, please let me know.

**Comment by ejthan** [comment]
I would be very interested to add plugins. However, I'm not quite sure how to implement the class call ('[new weekSelect({})]') without eval().

**Comment by rwwagner90** [comment]
@ejthan I am not familiar with these plugins. What changes do we need?
