### ISSUE TITLE
Best way to implement without an input field?

### ISSUE THREAD

**Issue by adambedford** [shipshapecode/ember-flatpickr#228]
I'm building an inline-edit component and I'd like to show the datepicker when the date label is clicked on (i.e. there is no form / no inputs).

This is similar to flatpickr's `wrap` option except that I don't want an input at all.

Any guidance on the best way to approach this with ember and this plugin?

**Comment by rwwagner90** [comment]
Are you not going to show the date the user picked after they pick it? That value is populated in the input. I would recommend maybe styling the input to just look like text by removing the border and such. I did something similar with this addon https://github.com/shipshapecode/ember-x-editable check out the demo on there.

**Comment by adambedford** [comment]
@rwwagner90 Thanks for your response. Your suggested approach works nicely!
