### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by seansellek** [shipshapecode/ember-flatpickr#229]
The dependency `ember-diff-attrs` causes a deprecation warning when run with 2.18:

`DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   DependencyVersionChecker.NPMDependencyVersionChecker (/Users/ssellek/Impinj/new-imc/threshold-monitor/node_modules/ember-diff-attrs/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:32)`

They have released a fix, covered here: https://github.com/workmanw/ember-diff-attrs/issues/8, with version 0.2.1.

Bump the required version from `0.2.0` -> `0.2.1` in order to avoid this deprecation.

**Comment by rwwagner90** [comment]
Merged the PR, so closing this. Thanks!
