### ISSUE TITLE
test: Unable to import test-helpers in ember 3.0 (i.e. isFlatPickerOpen, setFlatpickrDate etc..)

### ISSUE THREAD

**Issue by dbendaou** [shipshapecode/ember-flatpickr#244]
You've added `ember-native-dom-helpers` in devDependencies but if you don't have this package in your project it will fail 

And `start-app.js` is no longer required in ember 3 so the helpers should be imported in `test-helpers.js`

**Comment by rwwagner90** [comment]
Would you be interested in submitting a PR to fix those things up? 😄

**Comment by dbendaou** [comment]
Why not i will try to submit one before the end of the week :) 👍

**Comment by rwwagner90** [comment]
@dbendaou I believe I fixed this issue, and it no longer uses ember-native-dom-helpers. Can you confirm?

**Comment by dbendaou** [comment]
Yep, `ember-native-dom-helpers` is no longer needed
