### ISSUE TITLE
trigger time  by button

### ISSUE THREAD

**Issue by chenxu-javascript** [shipshapecode/ember-flatpickr#247]
My English is not good.  i want you can help me.
now. i want to trigger time control via button.
such as . 
the  first way
![image](https://user-images.githubusercontent.com/16332458/38775297-66092742-40b1-11e8-9b3c-cc5b8ed6d364.png)

![image](https://user-images.githubusercontent.com/16332458/38775320-bd7fcec2-40b1-11e8-812a-a294e3439fe2.png)

![image](https://user-images.githubusercontent.com/16332458/38775313-a0ec7ff8-40b1-11e8-8090-2540a48299ae.png)

when i click this  actions .  the  button is always  open. i guess the icon as external elements。

the second way
use wrap = true

![image](https://user-images.githubusercontent.com/16332458/38775336-775b0370-40b2-11e8-8fc5-fae1ae6decd9.png)

Can you tell me the correct way?  thank you  again

**Comment by rwwagner90** [comment]
`flatpickrRef.toggle()` did not work? It looks like you are not passing `date` into the component, which is likely to break things.
