### ISSUE TITLE
input-date: unable to type a date unless I press enter after + clicking on wanted date

### ISSUE THREAD

**Issue by dbendaou** [shipshapecode/ember-flatpickr#249]
Hi, it's me again 🙄

Don't know if it's a bug or bad ux, but when the `allowInput` option is activated,
you need to type your wanted `date` THEN you need to press enter and THEN to click on the wanted date. 
I would like to only type the date and don't be forced to press enter and then click on the date which is a bit frustrating..

There is a gif of the behavior
![may-02-2018 14-55-15](https://user-images.githubusercontent.com/15218861/39524338-eb1df74a-4e18-11e8-9317-b6d618788048.gif)
ps: notice that the error in french on the right mean "The field cannot be empty"
pss: we doesn't see the mouse cursor but I'm just clicking away on a other field after typing my date

**Comment by dbendaou** [comment]
If it's unclear, i would be happy to explain it in another way 😃

**Comment by rwwagner90** [comment]
@dbendaou does this error happen with flatpickr itself as well or just when using ember-flatpickr?

**Comment by rwwagner90** [comment]
If this is confirmed to be an ember-flatpickr issue, we can definitely try to fix it. I don't have the time to investigate if it is a flatpickr bug right now.

**Comment by dbendaou** [comment]
It seems to came from flatpickr bad implementation.. https://jsfiddle.net/xxmp01qk/

I'm closing this issue since it doesn't came from this repo. Thanks for the help

**Comment by rwwagner90** [comment]
I would recommend opening an issue on the flatpickr repo, if there is an error, and linking back here please.

**Comment by efx** [comment]
I think this is the upstream issue: https://github.com/flatpickr/flatpickr/issues/1551
