### ISSUE TITLE
Relax flatpickr version constraint

### ISSUE THREAD

**Issue by nragaz** [shipshapecode/ember-flatpickr#251]
Hardcoding the point release of flatpickr means that users of this add-on can't benefit from bug fixes, as in the recently released v4.4.5 and v4.4.6. A `~` or `^` constraint would be very helpful!

**Comment by rwwagner90** [comment]
Flatpickr frequently has bugged releases, which break ember-flatpickr, so it is locked to be on the safe side. I used to have `^`, and ended up with a ton of bugs, but we can try adding it back for awhile.

**Comment by rwwagner90** [comment]
I bumped the version and added back `^`. Hope this helps!

**Comment by nragaz** [comment]
Thank you!
