### ISSUE TITLE
disable : Is it possible to use it with a function?

### ISSUE THREAD

**Issue by bsylvain** [shipshapecode/ember-flatpickr#253]
Flatpickr can use a function for disable : https://flatpickr.js.org/examples/#disabling-dates

I cannot make it work in ember-flatpickr, is there any example of disable used with a function ?

**Comment by rwwagner90** [comment]
@bsylvain can you please share what you have tried? We're just passing the options to flatpickr, so it should support the same things.

**Comment by bsylvain** [comment]
I managed to get it working, I needed to put the fonction in an array and use arrow function to be able to use this.get().

**Comment by rwwagner90** [comment]
Glad to hear it works for you!
