### ISSUE TITLE
altFormat not binded?

### ISSUE THREAD

**Issue by Techn1x** [shipshapecode/ember-flatpickr#255]
I have something like this

Template
```handlebars
{{ember-flatpickr
  allowInput=true
  altFormat=altFormat
  altInput=true
  date=(readonly (moment-format startDate))
  model='single'
  onChange=(action 'startDateChanged')
}}
```

Controller
```javascript
altFormat: computed('startDate', function() {
  let startDate = this.get('startDate');
  let result = (startDate.someCondition) ? "j M (h:iK)" : "j M (h:iK) Y";

  console.log(result);
  return result;
}),
```

Basically, altFormat is definitely being changed when it is meant to, but the string displayed in the flatpickr input is not changing to the new altFormat string.

https://ember-twiddle.com/3a64d259966a1494315cd20ead8b4959?openFiles=controllers.application.js%2C

Should it be binded? If not, is there a way I can still do this?

Thanks

**Comment by rwwagner90** [comment]
It's not currently one of the things we update. It could potentially be added though. It would need to be added here https://github.com/shipshapecode/ember-flatpickr/blob/master/addon/components/ember-flatpickr.js#L53

**Comment by Techn1x** [comment]
Cool, thanks for that, I'll submit a PR when I get some free time

**Comment by Techn1x** [comment]
https://github.com/shipshapecode/ember-flatpickr/pull/256
