### ISSUE TITLE
ember-source v.3.4 => Deprecate component#sendAction

### ISSUE THREAD

**Issue by danielspaniel** [shipshapecode/ember-flatpickr#264]
Hi there. Looks like you are still using sendAction somewhere in the flatpicker component, and ember now deprecates that.  Do you have time to fix that?  If you need a hand let me know.

**Comment by rwwagner90** [comment]
Hi @danielspaniel we're using it in several spots. We should use closure actions instead. I'd be open to a PR if you would like.

**Comment by danielspaniel** [comment]
Actually, I realize I have to fix my own addons Robert, so I will let you get this one for now.

**Comment by Kilowhisky** [comment]
Here's the PR for it.

**Comment by rwwagner90** [comment]
This was closed by #266
