### ISSUE TITLE
Problem with setting date to array

### ISSUE THREAD

**Issue by bracke** [shipshapecode/ember-flatpickr#285]
Hi 

I'm using emner-flatpickr in range mode and want to supply two values at start values, but I get an exception:

"Assertion Failed: {{ember-flatpickr}} requires a `date` to be passed as the value for flatpickr."

{{ember-flatpickr
          locale="da"
          mode="range"
          nextArrow=">"
          date=['01-01-2011', '12-12-2016']
          dateFormat="d-m-Y"
          altFormat="Y-m-d"
          minDate=minDate
          onChange=(action "setDateRange")  
          placeholder="Vælg en periode..."
          prevArrow="<"
          weekNumbers=true
          classNames="form-control"
        }}

**Comment by rwwagner90** [comment]
I don't think the example you provided is valid handlebars.

`date=['01-01-2011', '12-12-2016']` would not work. You would have to setup an array in your JS and pass it down.

**Comment by bracke** [comment]
I have tried with an array in js, but it seemed to make flatpickr ignore the mode=range setting so it only took the first value.

But I found out what was wrong - it was the mindate - it was later than one of the values in the range!
I adjusted and now it works :-)

Thanks for responding.

Happy New Year.
