### ISSUE TITLE
Empty date value with placeholder support?

### ISSUE THREAD

**Issue by lifeart** [shipshapecode/ember-flatpickr#289]
```hbs
{{ember-flatpickr
    date=""
    enableTime=false
    placeholder="my text"
}}
```
same for 
```hbs
{{ember-flatpickr
    date=null
    enableTime=false
    placeholder="my text"
}}
```

produce init error

**Comment by rwwagner90** [comment]
It definitely works as `null`. See https://github.com/shipshapecode/ember-flatpickr/blob/master/tests/dummy/app/controllers/docs/components/ember-flatpickr.js#L6

An `onChange` is required though https://github.com/shipshapecode/ember-flatpickr/blob/master/addon/mixins/flatpickr.js#L24

Perhaps that's your issue?

**Comment by lifeart** [comment]
@rwwagner90 thank you for quick response! I have `onChange` as well, going to digg back to my code, and close this issue until I can reproduce it using ember-twiddle.

**Comment by lifeart** [comment]
It will be nice to add assert check for 'dateFormat` is string

**Comment by lifeart** [comment]
`dateFormat` should be string, but due to some issue it was undefined in my wrapper component. and this is produce hard-to-debbug issue, mentioned in ember-twiddle link.

![image](https://user-images.githubusercontent.com/1360552/50918737-1a24bd80-1452-11e9-8219-543b64b27a71.png)

**Comment by lifeart** [comment]
just to save time for next users, I can add kinda assert validation for `dateFormat` if it's present in params
