### ISSUE TITLE
OnChange, the value in the store become an array

### ISSUE THREAD

**Issue by bsylvain** [shipshapecode/ember-flatpickr#298]
I am handling a date object, and I only wnat to modify the date from a DS object : 

          {{ember-flatpickr
            dateFormat='d/m/Y'
            date=(readonly model.shop_data_user.last_contact)
            onChange=(action (mut model.shop_data_user.last_contact))}}

When I change It, in the ember inspector the new date is now the single item of an array. How can I correct that?

**Comment by rwwagner90** [comment]
Flatpickr passes arrays of selected dates, and our `onChange` wrapper does the same. https://github.com/shipshapecode/ember-flatpickr/blob/master/addon/mixins/flatpickr.js#L128

You'll want to define your on `onChange` action, rather than using `mut`. Something like this:

```hbs
{{ember-flatpickr
        dateFormat='d/m/Y'
        date=(readonly model.shop_data_user.last_contact)
        onChange=(action "customOnChange")}}
```

```js
actions: {
  customOnChange(selectedDates) {
    this.set('model.shop_data_user.last_contact', selectedDates[0]);
  }
}
```

**Comment by roberkules** [comment]
this should also work:

```
onChange=(action (mut model.shop_data_user.last_contact) value="firstObject")
```
