### ISSUE TITLE
Add today button to flatpickr

### ISSUE THREAD

**Issue by teakap** [shipshapecode/ember-flatpickr#308]
Hey, I am want to add a 'today' button on the ember-flatpickr. 

I found this [plugin](https://github.com/jcsmorais/shortcut-buttons-flatpickr) but I can't make it work. 
Maybe it's out of scope, cause already the flatpickr doesn't support a today button, but I believe many people would like this feature. 

Another approach would be to add the button by using [ember-elsewhere](https://github.com/ef4/ember-elsewhere/tree/master/tests/dummy/app/templates/components)
although I couldn't target the `.flatpickr-calendar` to add the button.

Is there another option I could use for this?

**Comment by rwwagner90** [comment]
Hi @teakap, we could add this functionality to this addon. Would you be interested in working on it?

**Comment by teakap** [comment]
Sure. I cloned the repo, but I wasn't able to understand how the code works. I was expecting to find something like components ex. `flatpickr-months`. Am I cloning the correct repo?  When I run it it shows the page of the docs. Probably I'm missing something huge, but can't figure it out :)

**Comment by teakap** [comment]
Nevermind, I got it. You extend the flatpickr. So actually.. if we want to add properly a today btn, I will need to make a PR to the [flatpickr](https://flatpickr.js.org/).

**Comment by teakap** [comment]
Connected with this one, I am trying to implement the [plugin](https://github.com/jcsmorais/shortcut-buttons-flatpickr) I mentioned you above. The way to initiliaze the plugin is something like: 

```javascript 

flatpickr("#calendar", {
  plugins: [
    ShortcutButtonsPlugin({
      button: [
        {
          label: "Beginning Of Time"
        }
      ],
      label: "or",
      onClick: (index, fp) => {
        fp.setDate("1970/01/01 00:00");
      }
    })
  ]
});

```

https://codepen.io/jcsmorais/pen/BxLzZV

I am trying to do the same on `didInsertElement` hook on `my-datepicker` component. 
like so: 
```javascript 
import ShortcutButtonsPlugin from 'shortcut-buttons-flatpickr';
.... 

    didInsertElement() {
       this.flatpickrRef("#calendar", {
            plugins: [
                ShortcutButtonsPlugin({
                    button: [{
                        label: "Beginning Of Time"
                    }],
                    label: "or",
                    onClick: (index, fp) => {
                        fp.setDate("1970/01/01 00:00");
                    }
                })
            ]
        });
    },
```
and my `my-datepicker.hbs`

```handlebars

    {{ember-flatpickr
        onChange=(action 'updateDate')
        getFlatpickrRef=(action (mut flatpickrRef))
        flatpickrRef=flatpickrRef
        altInput=true
        date=date
        id="calendar"
        altFormat="D, d M, Y"
    }}

```
 But I get this `this.flatpickrRef is not a function`. 

So I guess the flatpickrRef doesn't behave as flatpickr (like a constructor) right? 
Do you see any workarounds ?

**Comment by rwwagner90** [comment]
@teakap 

> Sure. I cloned the repo, but I wasn't able to understand how the code works. I was expecting to find something like components ex. flatpickr-months. Am I cloning the correct repo? When I run it it shows the page of the docs. Probably I'm missing something huge, but can't figure it out :)

The docs have a demo of the component functionality. You can play with the component there.

> Nevermind, I got it. You extend the flatpickr. So actually.. if we want to add properly a today btn, I will need to make a PR to the flatpickr.

ember-flatpickr wraps flatpickr. We are able to add extra functionality here. It could be an enhancement to ember-flatpickr, rather than flatpickr itself.

> So I guess the flatpickrRef doesn't behave as flatpickr (like a constructor) right?
Do you see any workarounds ?

`flatpickrRef` is set to the flatpickr reference, after it is initialized. The reason it is not defined here, is `didInsertElement` will run before the flatpickr is created.

`ember-flatpickr` passes everything down to flatpickr, so you should be able to create an instance of the plugin in `init` and pass it into `ember-flatpickr`.

Something like this:

```js
// my-datepicker.js

init() {
  this._super(...arguments);
  
  this.plugins = [
                ShortcutButtonsPlugin({
                    button: [{
                        label: "Beginning Of Time"
                    }],
                    label: "or",
                    onClick: (index, fp) => {
                        fp.setDate("1970/01/01 00:00");
                    }
                })
            ];
}
```

```hbs
{{ember-flatpickr
        onChange=(action 'updateDate')
        getFlatpickrRef=(action (mut flatpickrRef))
        flatpickrRef=flatpickrRef
        altInput=true
        date=date
        id="calendar"
        altFormat="D, d M, Y"
        plugins=this.plugins
    }}
```

Does this make sense?

**Comment by teakap** [comment]
Yiap, it totally makes sense! 

> ember-flatpickr wraps flatpickr. We are able to add extra functionality here. It could be an enhancement to ember-flatpickr, rather than flatpickr itself.

I will work on it to see how this can be implemented then! Thanks!
