### ISSUE TITLE
[Feature Request] `ignoredFocusElements` DOM element array

### ISSUE THREAD

**Issue by alexdiliberto** [shipshapecode/ember-flatpickr#311]
I have a component `<Foo/>` which displays `<EmberFlatpickr/>` from its component template. 

```hbs
// .../templates/components/foo.hbs
<EmberFlatpickr ignoredFocusElements=this.ignoredFocusElements/>

<button class="ignore-me">Ignore Me</button>
```

Within my `<Foo/>` component I want the ability to ignore Flatpickrs default/automatic closing behavior when only when clicking on some specific `.ignore-me` button also inside the `<Foo/>` component template

SEE:
https://github.com/flatpickr/flatpickr/issues/1159
https://github.com/flatpickr/flatpickr/blob/80e2576738a11969a92f08a3f048209cff6b1226/src/types/options.ts#L137-L139
https://github.com/flatpickr/flatpickr/blob/a4bf1d2da3e68502f19e370f306815e045ba2ebb/src/index.ts#L1439-L1441)

This won't work with the addon's current implementation as I need access to the specific DOM `HTMLElement[]` not it's string representation, so I would need to get the `.ignore-me` HTMLElement in my Foo Component's `didInsertElement()` hook but at this time we have passed the point of being able to alter values passed into `<EmberFlatpickr/>`.

**Comment by rwwagner90** [comment]
@alexdiliberto thanks for the issue! Would setting it later work? Like `flatpickrRef.set('ignoredFocusElements', [element])`?

**Comment by alexdiliberto** [comment]
@rwwagner90 Awesome, thanks for the prompt response. That worked actually worked perfect! Didn't realize Flatpickr had the setter which did the `redraw` and config option update. 💯 👍

**Comment by rwwagner90** [comment]
Awesome! Perhaps it would be worth documenting here?
