### ISSUE TITLE
"enableTime" option works incorrectly for the "range" mode

### ISSUE THREAD

**Issue by vigor-vlad** [shipshapecode/ember-flatpickr#322]
Hi @rwwagner90, first of all thanks for the great library, it works like a charm except one small issue that I've encountered. It looks like when we enable time selectors for the range picker
`{{ember-flatpickr enableTime=true mode='range'}}`
it works incorrectly.

I've prepared a twiddle:
https://ember-twiddle.com/98718ebe477d6ed792312557c158aa9a

When we select the first date (both start and end dates are null by default), the time picker works fine for it. But if the range is already selected and we start to change the range by clicking on a new date, the time picker stops working for it (the time picker is shown, but changing it has no effect), however it does work for the second date of the range. Looks like a binding issue to me.

If we manually clear the input and start selecting dates - it works once again.

Looks like the issue is not in the flatpickr library itself, as I've checked it and it works fine, but in the ember addon.

Could you please take a look at the issue, as you are more familiar with the code?

Best regards,
Vlad

**Comment by rwwagner90** [comment]
@vigor-vlad seems like perhaps something flatpickr could do better. I didn't even realize you could select times for range mode. The experience is a bit wonky there. I will see if anything jumps out at me as a fix.

**Comment by rwwagner90** [comment]
@vigor-vlad I believe your issue is you had not defined an `onChange`. I updated the twiddle to work https://ember-twiddle.com/f17668f4aec3676890ad4eb3e5c465bf

I also updated the docs, which now has a working example https://shipshapecode.github.io/ember-flatpickr/docs/components/ember-flatpickr#range-date-time-picker

Please let me know if this works for you!

**Comment by vigor-vlad** [comment]
@rwwagner90 thanks for your quick feedback! Well, I've removed the handler on purpose in the example, because the result was the same. In my app the handler is defined, of course 8). The actual fix for the issue is the switch from `2.14.1` to `2.14.3` release, that did the trick! 

Once again, thanks for your great work and sorry for bothering you. I should have noticed myself that I was using an old version 8(

**Comment by rwwagner90** [comment]
@vigor-vlad glad everything is working for you now! I just released those versions this morning, but didn't really change anything. Perhaps it was just from updating deps.
