### ISSUE TITLE
Ember serve failing to import stylesheet after install

### ISSUE THREAD

**Issue by linearza** [shipshapecode/ember-flatpickr#367]
Hi! I've gone through the issues and see there are similar issues, and tried moving the addon to deps instead of devDep, but on serve build is failing with:

```
Error: Can't find stylesheet to import.
  ╷
8 │ @import '../components/p-calendar/style';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Im on
```
ember-cli: 3.8.2
node: 8.12.0
os: darwin x64
```

**Comment by linearza** [comment]
Ok it seems the addon might not be the issue, though you might need to `_super` your sass includes. 
Related ember-cli issue:
https://github.com/ember-cli/ember-cli/issues/8026
Fix which provided the fix for me:
https://github.com/ember-cli/ember-resolver/issues/304
https://github.com/lstrzebinczyk/ember-unified-structure-with-modal/pull/1/files

In my `ember-cli-build.js` I just added:
```
sassOptions: {
      includePaths: [
        'app/styles'
      ],
      onlyIncluded: false
    },
```

Closing.

**Comment by rwwagner90** [comment]
@linearza not sure I understand. We use ember-cli-node-assets to ship the JS and theme CSS file.
