### ISSUE TITLE
Updating altInputClass (with bootstrap's is-invalid class after validation) doesn't update the class in the DOM

### ISSUE THREAD

**Issue by roberkules** [shipshapecode/ember-flatpickr#391]
basically I'm trying to change the input class after the form is submitted (and there's an error):

```hbs
{{ember-flatpickr
  altInputClass=(concat "form-control" (if errorMessage " is-invalid"))
}}
```

but when there's an error, the DOM input element is not updated with the `is-invalid` class

**Comment by rwwagner90** [comment]
@roberkules I think it would need to be added to `didReceiveAttrs` https://github.com/shipshapecode/ember-flatpickr/blob/master/addon/mixins/flatpickr.js#L46

Would you be interested in trying your hand at a fix?
