### ISSUE TITLE
Allow date to be undefined

### ISSUE THREAD

**Issue by Samsinite** [shipshapecode/ember-flatpickr#435]
Hi, love the addon, thanks for the hard work!

There is one part of the addon that can make it harder to use, the requirement that the date cannot be undefined. For example, something like `@date={{model.someDate}}` requires that the model does not allow `someDate` to ever be `undefined`, which can require extra setup/configuration on the models. While this is easy enough to do for most experienced developers, it can sometime cause confusion with newer developers. So, it would be nice if this component worked with dates that are `undefined` in addition to `null`.

**Comment by rwwagner90** [comment]
@Samsinite I don't think we are likely to support this. It is easy enough to set the value to null explicitly if you meant to have no value.
