### ISSUE TITLE
API reference that defines all ember-flatpickr options - does this exist?

### ISSUE THREAD

**Issue by tracyalison11** [shipshapecode/ember-flatpickr#442]
I can't find anything in the documentation that defines attributes (e.g. appendDataInput or locale). It would be great to have more information on these (if it doesn't already exist). I would be happy to get something started but want to ensure I'm not missing the references that already exist. Thanks!

**Comment by rwwagner90** [comment]
Hi @tracyalison11, https://shipshapecode.github.io/ember-flatpickr/docs/usage shows many of the options, but it may be out of date. All of the flatpickr options should be supported though https://flatpickr.js.org/options/

If you would like to document things in more depth, we would gladly help with a PR 😃

**Comment by tracyalison11** [comment]
Thanks so much for pointing me in the right direction - that was very helpful!

**Comment by rwwagner90** [comment]
@tracyalison11 you're welcome! Do you think we should document things further or is pointing to the flatpickr docs sufficient?
