### ISSUE TITLE
Helper could not be found

### ISSUE THREAD

**Issue by Swizz** [shipshapecode/ember-flatpickr#5]
Hi, 
I am encountering something really weird.
After installing this addon (as I have always done), I met in the console and input was not show :

```Uncaught Error: Assertion Failed: A helper named 'ember-flatpickr' could not be found```

I tried to relaunch server, reinstall, and generate addon, but nothing works.

This is the first time I meet this. How to solve it ?

Regards,

**Comment by Swizz** [comment]
I think, this is due to the pod structure of the component (?).
I am using ember-cli 2.5.

So I solved this issue with a little trick.

```js
/* components/ember-flatpickr/component.js */

import emberFlatpickr from 'ember-flatpickr/components/ember-flatpickr/component';

export default emberFlatpickr;
```

**Comment by rwwagner90** [comment]
@Swizz could you confirm the version you have installed? I recently switched from using ember-browserify to just using flatpickr as a bower dependency, so doing a fresh `ember install ember-flatpickr` should run the blueprint and pull in flatpickr from bower. Not sure if that is contributing to this issue or not.

**Comment by Swizz** [comment]
@rwwagner90  Sure, I am dealing with

```json
/* from npm */
"ember-cli": "2.5.0",
"ember-flatpickr": "0.1.11"

/* from bower */
"ember": "~2.5.0",
"flatpickr": "flatpickr-calendar#1.8.8"
```

But ... the bower dependencie seem to be pulled, because, the proxy component works well.
The weird thing is around the component/helper registering.

It is really uncommon, I installed a new addon, and It works well at the first time.

**Comment by rwwagner90** [comment]
@Swizz seems like all the versions should be fine then. If you start from scratch and install, everything works though, right?

**Comment by NullVoxPopuli** [comment]
I have this issue as well. But, I am using pods.

**Comment by rwwagner90** [comment]
@NullVoxPopuli can you please do the following?

1. Remove ember-flatpickr from your package.json
1. Remove flatpickr from your bower.json
1. `rm -rf node_modules bower_components`
1. `npm i`
1. `bower i`
1. `ember install ember-flatpickr`

Let me know if clearing everything out works or not, and then please confirm the versions of ember-flatpickr and flatpickr you have.

**Comment by NullVoxPopuli** [comment]
I'll give that a go tonight.
I wasn't blocked or anything, thanks to @Swizz's technique of convincing the resolver ember-flatpickr really does exist.

**Comment by rwwagner90** [comment]
@NullVoxPopuli if it still doesn't find it, it is probably a bug with pods themselves, as I'm just using the standard addon exports, which should register it to the app namespace.

**Comment by rwwagner90** [comment]
@NullVoxPopuli I wonder if there is an issue with me using pods in the addon and you then using the component inside another pod? Perhaps I should put the addon back to normal structure, not pods?

**Comment by NullVoxPopuli** [comment]
Yeah.

My bet would be on that if the error persists, it has to do with my app still being in transition, and having traditional structure and pods structure (under `app/pods/`)

**Comment by NullVoxPopuli** [comment]
I'd keep your component as pods and then maybe provide the 'hack' that I have? https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/app/components/ember-flatpickr.js

**Comment by NullVoxPopuli** [comment]
cause, my hunch is this is a pods issue

**Comment by NullVoxPopuli** [comment]
(get hyped for ember's module unification!!)

**Comment by rwwagner90** [comment]
@NullVoxPopuli yeah, it feels like a pods issue, but I don't know if it would be an issue, if I didn't use pods here too. Would you like to submit a PR to update the README with something like "if you get the error (whatever the error is), use this hack"? Would be an easy contribution 😃 

So ready for module rfc to be implemented!

**Comment by rwwagner90** [comment]
@Swizz @NullVoxPopuli I switched this addon to use traditional structure, instead of pods, and it appears to fix the issue. Please grab 0.7.0 and delete your workaround files 😄
