### ISSUE TITLE
Date format is not working

### ISSUE THREAD

**Issue by zipme** [shipshapecode/ember-flatpickr#6]
Hi, 

It seems the dateFormat does not work?

So I pass in `dateFormat="m/d/Y"` but after I select a date the field still displays `Thu Jul 14 2016 00:00:00 GMT+0800 (CST)`

The demo page seems also broke too?

**Comment by zipme** [comment]
I think I found the reason why this happen:

https://github.com/shipshapecode/ember-flatpickr/blob/master/addon/components/ember-flatpickr/component.js#L38

I think this line of code set the `value` of the component which overwrites the formatted value

**Comment by rwwagner90** [comment]
Hi @zipme this could definitely be true. Do you have a proposed solution?

**Comment by rwwagner90** [comment]
Seems to me that the dateObject from flatpickr should respect the formatting you pass in, as this would be an issue for anyone using flatpickr, and not just using ember-flatpickr.

**Comment by zipme** [comment]
@rwwagner90 that's true. But for now I think we can remove `this.set('value', dateObject);`
and simply use the `onChangeAction` to get the selected date like this:
```handlebar
{{ember-flatpickr
  dateFormat="m/d/Y"
  val=(mut model.estDeliveryDate)
  onChangeAction=(action (mut selectedDate))
}}
```

**Comment by rwwagner90** [comment]
@zipme that will still pass the same dateObject to the onChangeAction though, so it should have the same issue right?

**Comment by zipme** [comment]
@rwwagner90 sorry, I forgot to remove the val= in the code I pasted, so after `this.set('value', dateObject);` is removed. I use the component like this:
```
{{ember-flatpickr
  dateFormat="m/d/Y"  
  onChangeAction=(action (mut selectedDate))
}}
```
Which works perfectly, and you are right that `dateObject` will be passed to `onChangeAction` but that's what I want since my `selectedDate` is a date type, and the date displayed in the ember-flatpickr will be what the format specified since we didn't alter the `value` anymore.

**Comment by rwwagner90** [comment]
@zipme I noticed that onChange has `dateObject` and `dateString`. I wonder if the string one is formatted correctly? I'd really like to keep the automatic setting of the value, if we can, that way people who do not want/need to define an `onChangeAction` just have it automatically updating as expected.

**Comment by zipme** [comment]
@rwwagner90 I think the dateString is correctly formatted, but even so, I still think the `value` should be of date type instead of string, since it's a `date picker` it makes more sense to have its value as an date object instead of string, perhaps we can add another property called `dateString` or something?

**Comment by rwwagner90** [comment]
@zipme I'm definitely open to a PR that supports both cases 😄

**Comment by rwwagner90** [comment]
@zipme did you have a solution in mind that supports both cases? If not, I can try to knock this out this week sometime, but I would love a PR if you have the time and a solution in mind.

**Comment by zipme** [comment]
hi @rwwagner90 , sorry for the late reply, I was too busy lately. I am currently using a dirty hack to workaround this issue, would definitely send a PR somewhere next week, but if this is too late, maybe you can also try it out, what I have in mind is a similar API to ember-power-select component.

**Comment by rwwagner90** [comment]
@zipme I'm quite busy as well, so I can definitely wait until you submit a PR, if you will be able to by next week.

**Comment by rwwagner90** [comment]
@zipme still think you can submit a PR this week?

**Comment by rwwagner90** [comment]
@zipme when do you think you might have some availability? If it won't be for awhile, I can try to take a look.

**Comment by zipme** [comment]
@rwwagner90 Sorry for the late reply, I had a long flight ;), Yeah I might give it a try this week ;)

**Comment by zipme** [comment]
hi @rwwagner90 , I think we'd better not set the `value` when the user selects the date. The reason is that shifting to one way bindings makes things easier to reason about (data down, actions up). Have a look at this add-on https://github.com/DockYard/ember-one-way-controls you will see what I mean ;) So it seems to me the fix to this issue would be just the deletion of one line of code.

**Comment by rwwagner90** [comment]
@zipme why would you want a datepicker where you didn't know the updated value, when a user selected something? We can't just delete it. We could require that the user pass an `onChange` function, but it would be nice for users to not need to do anything.

**Comment by zipme** [comment]
@rwwagner90 by using the `onChange` I can still get the updated value, and this pattern (one-way binding, data-down, actions-up) like I said is easier to reason about and easier to debug.

**Comment by rwwagner90** [comment]
@zipme I started on a PR to address this. Please take a look and let me know your thoughts https://github.com/shipshapecode/ember-flatpickr/pull/12

**Comment by zipme** [comment]
@rwwagner90 This is exactly what i meant 👍 , thanks!

**Comment by rwwagner90** [comment]
No problem @zipme! I am still seeing something weird though. If you just pass null as the `onChange` it seems like the value is still changing behind the scenes. The flatpickr appears correct, but if you are displaying out the value, like we do on the demo page, it seems to be one step behind the value changes from flatpickr.

**Comment by rwwagner90** [comment]
@zipme I think it was just a side effect of Ember being two way data binding by default. Passing as `value=(readonly dateValue)` seems to solve the problem

**Comment by rwwagner90** [comment]
Just merged my PR in, and released 0.4.0 of this addon. Please try it out and let me know if it works for you @zipme!

**Comment by zipme** [comment]
@rwwagner90 nice! I will give it a try. 🤘

**Comment by rwwagner90** [comment]
@zipme I also updated flatpickr to 1.9.1 and added several options we were missing. 0.6.0 is now the latest version. Please give it a try. I am going to close this issue and if you have any more issues please feel free to open another.

**Comment by zipme** [comment]
@rwwagner90 great! Thanks a lot!
