### ISSUE TITLE
Updating `clickOpens` arg is ignored

### ISSUE THREAD

**Issue by omairvaiyani** [shipshapecode/ember-flatpickr#643]
After this component is rendered, if `@clickOpens` changes from `true` to `false`, the underlying picker is not updated. Is there are workaround that doesn't involve re-rendering our component each time the arguments are updated?

**Comment by rwwagner90** [comment]
@omairvaiyani I'm a bit confused on the use case, but we could add something here to update it on update https://github.com/shipshapecode/ember-flatpickr/blob/master/addon/components/ember-flatpickr.hbs#L7

**Comment by rwwagner90** [comment]
@omairvaiyani could you explain your use case a bit more? We could easily add it if this is needed.
