### ISSUE TITLE
@onChange callback called without changing the current date 

### ISSUE THREAD

**Issue by usamahamed** [shipshapecode/ember-flatpickr#739]
Steps to reproduce: when i open the calender and close it again without changing the dates the `onChange` called with the beginning of current month which is not the intended behaviour 

browser: chrome

version: Latest

**Comment by rwwagner90** [comment]
@usamahamed we just pass this to flatpickr, so flatpickr must be calling the change then.

**Comment by usamahamed** [comment]
@rwwagner90 It is very serious issue because of the following: 

- we did some network actions when the date is changed and based on this we display some statistics number 
- i expect when I open and close the calendar without changing the date, the date remains the same and in this case, it will not be a problem because I can just skip it with a simple condition but the case is, it reset the current date and time with a default values 
- in this screenshot it reset the date to 1-May and time to 12:00:00

![image](https://user-images.githubusercontent.com/23267284/116846599-ea80bd00-abe8-11eb-9d16-6fe377d4a5bb.png)

**Comment by rwwagner90** [comment]
@usamahamed we're just passing `onChange` to flatpickr https://github.com/shipshapecode/ember-flatpickr/blob/master/addon/components/ember-flatpickr.ts#L125

This is not a bug here. 

What does your `onChange` look like? I expect you may have the wrong signature. https://flatpickr.js.org/events/#events
