### ISSUE TITLE
[Question] Format value and display

### ISSUE THREAD

**Issue by lypborges** [shipshapecode/ember-flatpickr#79]
Tks for this addon. ;)

I try to look in the docs of flatpickr but I couldn't find how to send a format to server but display another for the user. 
I need to send a iso8601 string, is that possible?

**Comment by rwwagner90** [comment]
`dateFormat` and `altFormat` are what you want. They should be documented on the flatpickr docs in the options section.

**Comment by lypborges** [comment]
Sorry, but I try that:

`
 {{ember-flatpickr
    dateValue=dateValue
    dateFormat='Y-m-d'
    altInput=true
    altFormat='Y-m-d'
    placeholder=placeholder
    value=dateValue
    onChange=(action (mut dateValue))
  }}
`

This show the date on right format `2016-12-30`, but when the AJAX is made the value that hits on the server is "Fri Jan 06 2017 00:00:00 GMT-0200 (BRST)". 

Sorry if I'm missing anything. Thanks for your response and help.

**Comment by rwwagner90** [comment]
Sounds like a bug in flatpickr itself. Your options look more or less correct. Could you try and see if using flatpickr directly, instead of ember-flatpickr has the same issue?

**Comment by rwwagner90** [comment]
Are you sending the AJAX call in the onChange or what? If you can create some sort of example, I can look into it.

**Comment by lypborges** [comment]
I'm sending the AJAX ou the form submit. May be I'm doing something wrong. I'll make a dummy project and share with you.

> Sounds like a bug in flatpickr itself. Your options look more or less correct. Could you try and see if using flatpickr directly, instead of ember-flatpickr has the same issue?

I'm not sure how to do that, but I'll try.

But, here are my code:
My component (ms-datepicker) .hbs
```html
`<div class="field">
  {{#if label}}
    <label>{{label}}</label>
  {{/if}}
  {{ember-flatpickr
    dateValue=dateValue
    dateFormat='Y-m-d'
    altInput=true
    altFormat='Y-m-d'
    placeholder=placeholder
    value=dateValue
    onChange=(action (mut dateValue))
  }}
</div>
```

The edit.hbs template

```html
The ms-datepicker is just one component from a form, so I ommited inputs and other html code.
{{ms-datepicker
        dateValue=model.date
        label=(t 'activity.labels.date')
        placeholder=(t 'activity.placeholder.date')
        enableTime=true}}
```

Sending from the route

```javascript 
import Ember from 'ember';

export default Ember.Route.extend({
  intl: Ember.inject.service(),
  model(params) {
    return this.store.findRecord('activity', params.activity_id);
  },
  actions: {
    onSave(activity) {
      activity.save().then(()=>{
        let message = this.get('intl').t('activity.saved');
        this.get('notifications').success(message);
        this.transitionTo('app.activities');
      }).catch((error) => {
        this.get('notifications').error(error);
      });
    },
    onCancel(){
      this.transitionTo('app.activities');
    }
  }
});
```

**Comment by lypborges** [comment]
Here is the demo. 

https://github.com/lypborges/sample_datepicker.git

**Comment by lypborges** [comment]
Tks for your help. I was getting the wrong param from onChange. I should get dateStr and not selectedDates.

```javascript
# Flatpickr code
/**
   * When the date is changed, update the value and send 'onChange' action
   * @param selectedDates The array of selected dates
   * @param dateStr The string representation of the date, formatted by dateFormat
   * @param instance The flatpickr instance
   * @private
   */
  _onChange(selectedDates, dateStr, instance) {
    if (selectedDates && selectedDates.length > 0) {
      this.sendAction('onChange', selectedDates, dateStr, instance);
    }
  },
```
```javascript
# My component action
onChange(selectedDates, dateStr, instance) {
     console.log(dateStr);
   }
```
