### ISSUE TITLE
Open via flatpickrRef not working

### ISSUE THREAD

**Issue by jgadbois** [shipshapecode/ember-flatpickr#89]
I'm attempting to open via an icon using the flatpickrRef and the calling `open()` on flatpickr.  It's calling the method correctly but the calendar won't actually show.

I'm calling like this

```
# component template
{{ember-flatpickr onChange=null flatpickrRef=calendar clickOpens=false allowInput=false}}

# in component
  calendar: null,
  actions: {
    showCalendar: function() {
      alert('toggling');
      this.get("calendar").open()
    }
   }
```

**Comment by rwwagner90** [comment]
@jgadbois does `this.get('calendar')` return a valid flatpickr instance?

**Comment by jgadbois** [comment]
Yes console.log gives me:

`Flatpickr {element: input#ember1014.ember-view.ember-text-field.flatpickr-input, instanceConfig: Object, formats: Object, config: Object, l10n: Object…}`

**Comment by rwwagner90** [comment]
Then perhaps `open` is bugged on flatpickr itself? Not entirely sure.

**Comment by jgadbois** [comment]
I'm not sure, I worked around it with `opacity: 0` on the input.  I'll close.

**Comment by rwwagner90** [comment]
@jgadbois I know I have seen some weird behavior where there are two flatpickrs and two inputs before. Unsure what the fix is. Would you be interested in helping debug?

**Comment by jgadbois** [comment]
Sure!  When I clicked with devtools open I did see the input classes flash, but the active class wasn't there, so maybe it opened then closed immediately?

**Comment by rwwagner90** [comment]
Can you tell if there are two inputs and two flatpickr instances?

**Comment by jgadbois** [comment]
No, just one instance

**Comment by rwwagner90** [comment]
Hmm, could you try using flatpickr directly, instead of this addon, and see if the same thing happens?

**Comment by jgadbois** [comment]
It works

http://codepen.io/anon/pen/oBgPKQ
