### ISSUE TITLE
Installation failed in Ember 3.28

### ISSUE THREAD

**Issue by kmichek** [shipshapecode/ember-flatpickr#914]
Hi, great plugin, using it for years, but with the last Ember version the installation fails (while other plugins install correctly):

> ember --version
ember-cli: 3.28.0
node: 12.16.3
os: darwin x64

> npm install ember-flatpickr
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/TowerArc/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN old lockfile 
npm ERR! npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm ERR! npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm ERR! npm WARN old lockfile 
npm ERR! npm WARN old lockfile This is a one-time fix-up, please be patient...
npm ERR! npm WARN old lockfile 
npm ERR! npm WARN deprecated exists-sync@0.0.4: Please replace with usage of fs.existsSync
npm ERR! npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! npm ERR! code ENOTFOUND
npm ERR! npm ERR! syscall getaddrinfo
npm ERR! npm ERR! errno ENOTFOUND
npm ERR! npm ERR! network request to https://artifacts.apple.com/api/npm/npm-private/yargs-parser/-/yargs-parser-17.0.0.tgz failed, reason: getaddrinfo ENOTFOUND artifacts.apple.com
npm ERR! npm ERR! network This is a problem related to network connectivity.
npm ERR! npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! npm ERR! network 
npm ERR! npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/TowerArc/.npm/_logs/2021-09-26T16_07_03_922Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/TowerArc/.npm/_logs/2021-09-26T16_07_04_173Z-debug.log

**Comment by rwwagner90** [comment]
@kmichek I do not see anything in there that looks like an error with ember-flatpickr. I see a lot of old lockfile warnings. Our test suite is passing up to ember canary, so it should be working.

**Comment by kmichek** [comment]
Hi, thank you for your answer. The same is happening after deleting the package-lock.json. There is a bit more info in the log, a part of it says:

3620 timing idealTree:node_modules/ember-flatpickr/node_modules/universalify Completed in 0ms
3621 timing idealTree:node_modules/ember-flatpickr/node_modules/walk-sync Completed in 0ms
3622 timing idealTree:buildDeps Completed in 84544ms
3623 timing idealTree:fixDepFlags Completed in 27ms
3624 timing idealTree Completed in 120079ms
3625 timing command:install Completed in 120085ms
3626 verbose stack Error: git dep preparation failed
3626 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
3626 verbose stack     at ChildProcess.emit (events.js:310:20)
3626 verbose stack     at maybeClose (internal/child_process.js:1021:16)
3626 verbose stack     at Socket.<anonymous> (internal/child_process.js:443:11)
3626 verbose stack     at Socket.emit (events.js:310:20)
3626 verbose stack     at Pipe.<anonymous> (net.js:672:12)
3627 verbose cwd /Users/... my project...
3628 verbose Darwin 20.6.0
3629 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "--loglevel error" "ember-flatpickr"
3630 verbose node v12.16.3
3631 verbose npm  v7.19.0
3632 error code 1
3633 error git dep preparation failed

Also, this URL really is not accessible from my end: network request to https://artifacts.apple.com/api/npm/npm-private/yargs-parser/-/yargs-parser-17.0.0.tgz failed, reason: getaddrinfo ENOTFOUND artifacts.apple.com

If it works for you then it must be something wrong on my box or something with my ISP / DNS, I need to investigate.

**Comment by rwwagner90** [comment]
@kmichek I still don't see a specific error here. If you get more info, I am happy to debug!

**Comment by kmichek** [comment]
Sorted. Was caused by wrong Ember version. I have uninstalled Ember and installed the latest version, then this plugin works perfect. My fault, sorry.
