### ISSUE TITLE
git dep preparation error - getaddrinfo ENOTFOUND artifacts.apple.com

### ISSUE THREAD

**Issue by carlosgalveias** [shipshapecode/ember-flatpickr#920]
Hi , so we use your module as a dependency and when we updated npm version, it started failing with error:

git dep preparation failed:
...
request to https://artifacts.apple.com/api/npm/npm-private/yeast/-/yeast-0.1.2.tgz failed, reason: getaddrinfo ENOTFOUND artifacts.apple.com

The issue comes from the dependency that is pointing to a very specific git commit:

"@ember/render-modifiers": "cibernox/ember-render-modifiers#e3574ed03409ef7a048d7716b8bea361ed6cd6e2",

that has a package-lock.json where all dependencies are pointing to artifacts.apple.com and that does not resolve, creating the error.

Any reason why that dependency is not pointing directly to @ember/render-modifiers but to a fork?

**Comment by rwwagner90** [comment]
Yes, render-modifiers does not work with Ember 4. It is pointing to this fork on purpose and will not be changed until render-modifiers merges the PR.

**Comment by happydude** [comment]
I'm having this problem too. One thing I discovered is with npm@6.14.15 it installs fine but with npm7 :

```
npm@7.24.1
npm ERR! npm ERR! code ENOTFOUND
npm ERR! npm ERR! syscall getaddrinfo
npm ERR! npm ERR! errno ENOTFOUND
npm ERR! npm ERR! network request to https://artifacts.apple.com/api/npm/npm-private/yeast/-/yeast-0.1.2.tgz failed, reason: getaddrinfo ENOTFOUND artifacts.apple.com
npm ERR! npm ERR! network This is a problem related to network connectivity.
npm ERR! npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! npm ERR! network 
npm ERR! npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

```

**Comment by carlosgalveias** [comment]
@rwwagner90 please make a pull of that intended commit on render-modifiers, look at the package-lock.json that it brings, try to do a npm install with npm >7. 
As it will try do adjust the package-lock (git dep preparation stage) to a new version , it will fail to do so because the package lock repository information is a internal apple address.
