### ISSUE TITLE
setFlatpickrDate leads to onChange being called with empty array

### ISSUE THREAD

**Issue by st-h** [shipshapecode/ember-flatpickr#975]
I am using the helper in my tests like this:
```
setFlatpickrDate('[data-test-date-field]', new Date('2120-12-12 01:00:00'), true);
```
 I can then observe that the callback provided as onChange gets called, however the argument contains an empty array. I would expect it to contain the date provided by `setFlatpickrDate`. Is there anything wrong with my expectation?

**Comment by rwwagner90** [comment]
@st-h hmm, that seems correct. If flatpickr's `onChange` is called, I would expect this to be working. Do you perhaps have some time to debug?

**Comment by st-h** [comment]
Sorry about the noise. Today I was revisiting this issue and I can no longer reproduce it 🤷‍♀️
